site_name: SimplyBot
site_description: Inteligentny chatbot RAG z analizą dokumentów
site_author: SimplyBot Team
site_url: https://your-username.github.io/SimplyBot/

repo_name: your-username/SimplyBot
repo_url: https://github.com/your-username/SimplyBot
edit_uri: edit/main/docs/

theme:
  name: material
  language: pl
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Przełącz motyw
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Przełącz motyw
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true
  - mermaid2
  

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

nav:
  - Strona główna: index.md
  - Architektura: architecture.md
  - Instalacja: installation.md
  - Użycie: usage.md
  - API Reference: api-reference.md
  - Rozwój: development.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username/SimplyBot
    - icon: fontawesome/brands/discord
      link: https://discord.gg/your-discord